apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviestore  
spec:
  selector:
    matchLabels:
      app: moviestore
  template:
    metadata:
      labels:
        app: moviestore
    spec:
      containers:
      - name: moviestore
        image: kcontainerregistry.azurecr.io/moviestore
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: moviestore
spec:
  type: LoadBalancer
  selector:
    app: moviestore
  ports:
  - port: 80
    targetPort: 80

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: moviestoreapi
# spec:
#   selector:
#     matchLabels:
#       app: moviestoreapi
#   template:
#     metadata:
#       labels:
#         app: moviestoreapi
#     spec:
#       containers:
#       - name: moviestoreapi
#         image: kcontainerregistry.azurecr.io/moviestoreapi
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 6123

# apiVersion: v1
# kind: Service
# metadata:
#   name: moviestoreapi
# spec:
#   selector:
#     app: moviestoreapi
#   ports:
#   - port: 6789
#     targetPort: 6123



